# General Settings
name: Benjamin Schuch
job_title: Globetrotter & Software Engineer
email: bschuch@gmx.net
description: Benjamin Schuch | Globetrotter & Software Engineer
avatar: https://avatars1.githubusercontent.com/u/1689047?v=3&s=460
favicon: /favicon.ico
twitter_handler: chillyistkult
analytics_code: UA-53471280-1
disqus: chillyistkult

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/benjamin-schuch' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/chillyistkult' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: 'http://xing.to/benjaminschuch' }

# Modules Settings
show_categories: 0
show_tags: 0
show_mood: 0
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "http://www.chillyistkult.de"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
